nome = str(input('Digite seu nome completo: ')).strip()
print ('Muito prazer em te conhecer!')
pri = nome.split()
ult = nome.rsplit()
print ('seu primeiro nome é {}'.format(pri[0]))
print ('seu ultimo nome é {}'.format(ult[-1]))